### ISSUE TITLE
获取Cookie失败

### ISSUE THREAD

**Issue by ykaiqx** [Coaixy/QuickIcve#1]
获取Cookie失败

**Comment by ykaiqx** [comment]
@Coaixy

**Comment by Coaixy** [comment]
好的

发自我的 iPhone

在 2023年2月24日，12:00，XiaoXinYo ***@***.***> 写道：

﻿

获取Cookie失败

**Comment by Coaixy** [comment]
﻿好的

发自我的 iPhone

在 2023年2月24日，12:00，XiaoXinYo ***@***.***> 写道：

﻿

获取Cookie失败
