### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by ykaiqx** [Coaixy/QuickIcve#2]
<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Coaixy** [comment]
OK
________________________________
发件人: XiaoXinYo ***@***.***>
发送时间: 2023年2月24日 12:22
收件人: Coaixy/QuickIcve ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Coaixy/QuickIcve] 无法使用 (Issue #2)


Sent from PPHub<https://apps.apple.com/cn/app/id1314212521>

―

**Comment by Coaixy** [comment]
已修复
